<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OnJsonError" Id="{04de9f32-2713-40de-b467-93156e4d7e09}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FINAL OnJsonError EXTENDS AwaitableError
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="OnJsonError">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>