<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OnRequestError" Id="{3196f5e9-f6dc-4fe4-8eda-29b243c11ef9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FINAL OnRequestError EXTENDS AwaitableError
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="OnRequestError">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>