<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="StepChainResetter" Id="{dc7dbcc0-ea5e-4b09-bc26-2e6958033dce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK StepChainResetter IMPLEMENTS Callback
VAR_INPUT
	stepReference:REFERENCE TO UDINT;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="execute" Id="{9c3e1ca9-c3f1-4fcb-a1dc-e54cf5122f74}">
      <Declaration><![CDATA[
(* This is method get's exectued by the framework when the callback is triggered.
 It returns a step number which might be used together with Await to jump to a certain chain step
 after the callback code has been executed.*)
METHOD execute : UDINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[stepReference := 0;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="StepChainResetter">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="StepChainResetter.execute">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>